name: CI Actions

on:
  push:
    branches:
      - develop
      - main

jobs:
  check:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install package
        run: npm install
      - name: Lint
        run: yarn lint
      - name: Unit test
        run: yarn test:unit:cov
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/
          fail_ci_if_error: true
